name: Build QuokkADB firmware

on:
  push:
  workflow_dispatch:

jobs:
  build_quokkadb:
    name: Build firmware on Ubuntu 22.04
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v3
        with:
          path: quokkadb
          fetch-depth: "0"

      - name: Install packages
        run: |
            sudo apt-get update      
            sudo apt-get install -y python3-pip

      - name: Install platformio
        run: |
          sudo pip install platformio

      - name: Build firmware
        run: |
          cd quokkadb/src/firmware
          pio run -ve quokkadb

      - name: Rename firmware files
        run: |
          cd quokkadb/src/firmware
          utils/rename_quokkadb_binaries.sh

      - name: Upload binaries into build artifacts
        uses: actions/upload-artifact@v3
        with: 
          path: quokkadb/src/firmware/distrib/*
          name: QuokkADB binaries
